// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateNewUser(ctx context.Context, arg CreateNewUserParams) error
	GetUserByEmail(ctx context.Context, email string) (string, error)
	GetUserByUsername(ctx context.Context, username string) (string, error)
	GetUserDataByUserId(ctx context.Context, userID string) (GetUserDataByUserIdRow, error)
	GetUserDataByUsername(ctx context.Context, username string) (GetUserDataByUsernameRow, error)
	ListUserActive(ctx context.Context) ([]ListUserActiveRow, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) error
	UpdateUserLastActive(ctx context.Context, userID string) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error
	UserLogin(ctx context.Context, username string) (UserLoginRow, error)
}

var _ Querier = (*Queries)(nil)
