// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: usersDML_3.sql

package sqlc

import (
	"context"
)

const updateUserData = `-- name: UpdateUserData :exec
UPDATE Users
SET username = ?, full_name = ?, email = ?
WHERE user_id = ?
`

type UpdateUserDataParams struct {
	Username string `db:"username" json:"username"`
	FullName string `db:"full_name" json:"full_name"`
	Email    string `db:"email" json:"email"`
	UserID   string `db:"user_id" json:"user_id"`
}

func (q *Queries) UpdateUserData(ctx context.Context, arg UpdateUserDataParams) error {
	_, err := q.db.ExecContext(ctx, updateUserData,
		arg.Username,
		arg.FullName,
		arg.Email,
		arg.UserID,
	)
	return err
}
