// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: usersDML_3.sql

package sqlc

import (
	"context"
)

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE Users
SET full_name = ?, location = ?, website = ?
WHERE user_id = ?
`

type UpdateUserProfileParams struct {
	FullName string `db:"full_name" json:"full_name"`
	Location string `db:"location" json:"location"`
	Website  string `db:"website" json:"website"`
	UserID   string `db:"user_id" json:"user_id"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateUserProfile,
		arg.FullName,
		arg.Location,
		arg.Website,
		arg.UserID,
	)
	return err
}
