// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: users2.sql

package sqlc

import (
	"context"
)

const updateUserAvatar = `-- name: UpdateUserAvatar :exec
UPDATE Users
SET avatar = ?
WHERE user_id = ?
`

type UpdateUserAvatarParams struct {
	Avatar string `db:"avatar" json:"avatar"`
	UserID string `db:"user_id" json:"user_id"`
}

func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) error {
	_, err := q.db.ExecContext(ctx, updateUserAvatar, arg.Avatar, arg.UserID)
	return err
}
