// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: usersDML_2.sql

package sqlc

import (
	"context"
)

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE Users
SET password = ?
WHERE user_id = ?
`

type UpdateUserPasswordParams struct {
	Password string `db:"password" json:"password"`
	UserID   string `db:"user_id" json:"user_id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.Password, arg.UserID)
	return err
}
